# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
parameters:
  - name: message
    type: string

resources:
  pipelines:
    - pipeline: first
      source: zulu1990.MainPipeline
      trigger:    
        stages:         # This stage filter is used when evaluating conditions for 
        - NonProd        # triggering your pipeline. On successful completion of all the stages
        - RunTest       # provided, your pipeline will be triggered. 
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Running mocked tests
    echo delivered ${{ parameters.message }}
  displayName: 'Run a multi-line script'
